import cron from 'node-cron';
import { CategoryChannel, ChannelType, Client, EmbedBuilder, TextChannel } from 'discord.js';
import { fetchCategoryMessages, ensureSummaryChannel } from './messages';
import { summarizeCategory, ollamaModel } from './ollama';

const SUMMARY_CRON = process.env.SUMMARY_CRON ?? '0 22 * * *';
const WINDOW_HOURS = 24;

export function startScheduler(client: Client): void {
  cron.schedule(
    SUMMARY_CRON,
    () => runDailySummary(client),
    { timezone: 'Asia/Bangkok' },
  );
  console.log(`Scheduler started: "${SUMMARY_CRON}" (Asia/Bangkok)`);
}

export async function runDailySummary(client: Client, hoursBack = WINDOW_HOURS): Promise<void> {
  const now = new Date();
  const since = new Date(now.getTime() - hoursBack * 60 * 60 * 1000);

  console.log(`[ledger] Running summary: ${since.toISOString()} → ${now.toISOString()}`);

  for (const [, guild] of client.guilds.cache) {
    const categories = guild.channels.cache.filter(
      (c): c is CategoryChannel => c.type === ChannelType.GuildCategory,
    );

    for (const [, category] of categories) {
      try {
        await summarizeAndPost(category, since, now);
      } catch (err) {
        console.error(`[ledger] Failed for category "${category.name}" in "${guild.name}":`, err);
      }
    }
  }
}

async function summarizeAndPost(
  category: CategoryChannel,
  since: Date,
  now: Date,
): Promise<void> {
  const channels = await fetchCategoryMessages(category, since, now);
  const totalMessages = channels.reduce((n, c) => n + c.messages.length, 0);

  if (totalMessages === 0) {
    console.log(`[ledger] No messages in "${category.name}" — skipping`);
    return;
  }

  console.log(`[ledger] Summarizing "${category.name}": ${totalMessages} messages across ${channels.length} channels`);

  const summary = await summarizeCategory(category.name, channels, since, now);
  const summaryChannel = await ensureSummaryChannel(category.guild.client, category);

  const embed = buildSummaryEmbed(category.name, channels, summary, since, now);
  await summaryChannel.send({ embeds: [embed] });

  console.log(`[ledger] Posted summary to #${summaryChannel.name} in "${category.name}"`);
}

function buildSummaryEmbed(
  categoryName: string,
  channels: { channelName: string; messages: unknown[] }[],
  summary: string,
  since: Date,
  until: Date,
): EmbedBuilder {
  const fromStr = formatICT(since);
  const toStr = formatICT(until);
  const totalMsgs = channels.reduce((n, c) => n + c.messages.length, 0);
  const channelList = channels
    .filter((c) => c.messages.length > 0)
    .map((c) => `#${c.channelName} (${c.messages.length})`)
    .join(', ');

  return new EmbedBuilder()
    .setTitle(`Daily Summary — ${categoryName}`)
    .setDescription(summary.slice(0, 4000))
    .setColor(0x5865f2)
    .addFields(
      { name: 'Period', value: `${fromStr} → ${toStr} ICT`, inline: true },
      { name: 'Messages', value: String(totalMsgs), inline: true },
      { name: 'Channels', value: channelList || 'none', inline: false },
    )
    .setFooter({ text: `Generated by Ledger · ${ollamaModel()}` })
    .setTimestamp();
}

function formatICT(date: Date): string {
  return date.toLocaleString('en-GB', {
    timeZone: 'Asia/Bangkok',
    day: '2-digit',
    month: 'short',
    hour: '2-digit',
    minute: '2-digit',
  });
}
