import { CategoryChannel, ChannelType, ChatInputCommandInteraction, MessageFlags, SlashCommandBuilder } from 'discord.js';
import { BotCommand } from '../../types';
import { fetchCategoryMessages, ensureSummaryChannel } from '../../utils/messages';
import { summarizeCategory, ollamaModel } from '../../utils/ollama';
import { EmbedBuilder } from 'discord.js';

const command: BotCommand = {
  data: new SlashCommandBuilder()
    .setName('summarize')
    .setDescription('Generate a summary for this category right now')
    .addIntegerOption((opt) =>
      opt
        .setName('hours')
        .setDescription('How many hours back to look (default: 24)')
        .setMinValue(1)
        .setMaxValue(168),
    ) as SlashCommandBuilder,

  async execute(interaction: ChatInputCommandInteraction) {
    await interaction.deferReply({ flags: MessageFlags.Ephemeral });

    const channel = interaction.channel;
    if (!channel || channel.type !== ChannelType.GuildText) {
      await interaction.editReply('Run this command inside a text channel.');
      return;
    }

    const category = channel.parent;
    if (!category || category.type !== ChannelType.GuildCategory) {
      await interaction.editReply('This channel is not inside a category.');
      return;
    }

    const hours = interaction.options.getInteger('hours') ?? 24;
    const now = new Date();
    const since = new Date(now.getTime() - hours * 60 * 60 * 1000);

    await interaction.editReply(`Generating ${hours}h summary for **${category.name}**... this may take a minute.`);

    const channels = await fetchCategoryMessages(category as CategoryChannel, since, now);
    const totalMessages = channels.reduce((n, c) => n + c.messages.length, 0);

    if (totalMessages === 0) {
      await interaction.editReply(`No messages found in **${category.name}** over the past ${hours} hours.`);
      return;
    }

    const summary = await summarizeCategory(category.name, channels, since, now);

    let summaryChannel;
    try {
      summaryChannel = await ensureSummaryChannel(interaction.client, category as CategoryChannel);
    } catch (err: unknown) {
      const isPermission = err instanceof Error && err.message.includes('Missing Permissions');
      await interaction.editReply(
        isPermission
          ? 'Missing **Manage Channels** permission — either grant it to the ledger role in Server Settings → Roles, or manually create a `#bot-summary` channel in this category.'
          : `Failed to create #bot-summary: ${err instanceof Error ? err.message : String(err)}`,
      );
      return;
    }

    const embed = new EmbedBuilder()
      .setTitle(`Summary — ${category.name} (last ${hours}h)`)
      .setDescription(summary.slice(0, 4000))
      .setColor(0x57f287)
      .addFields(
        {
          name: 'Period',
          value: `${fmtICT(since)} → ${fmtICT(now)} ICT`,
          inline: true,
        },
        { name: 'Messages', value: String(totalMessages), inline: true },
      )
      .setFooter({ text: `Generated by Ledger · ${ollamaModel()}` })
      .setTimestamp();

    await summaryChannel.send({ embeds: [embed] });
    await interaction.editReply(`Summary posted to <#${summaryChannel.id}>.`);
  },
};

function fmtICT(date: Date): string {
  return date.toLocaleString('en-GB', {
    timeZone: 'Asia/Bangkok',
    day: '2-digit',
    month: 'short',
    hour: '2-digit',
    minute: '2-digit',
  });
}

export default command;
